site_name: Notas musicais
repo_url: https://github.com/eBetcel/notas-musicais
repo_name: eBetcel-notas-musicais
edit_uri: tree/main/docs
theme:
  name: material
  language: pt-BR
  #logo: assets/logo.png
  #favicon: assets/logo.png
